### ISSUE TITLE
Something wrong in 'build_spk_models.py' or 'pre-models'

### ISSUE THREAD

**Issue by CaptainCake** [FAKEBOB-adversarial-attack/FAKEBOB#1]
#### In step 6, when I run build_spk_models.py and I usd the _pre-models_ you provide, there are something wrong:
----- step 1: generate ivector identity and corresponding speaker model, setting threshold -----
--- extracting and scoring ---
/root/kaldi-trunnk/FAKEBOB/pre-models/utils/fix_data_dir.sh: file /root/kaldi-trunnk/FAKEBOB/audio-build-model-iv/utt2spk is not in sorted order or not unique, sorting it
/root/kaldi-trunnk/FAKEBOB/pre-models/utils/fix_data_dir.sh: file /root/kaldi-trunnk/FAKEBOB/audio-build-model-iv/wav.scp is not in sorted order or not unique, sorting it
fix_data_dir.sh: kept all 5316 utterances.
fix_data_dir.sh: old files are kept in /root/kaldi-trunnk/FAKEBOB/audio-build-model-iv/.backup
/root/kaldi-trunnk/FAKEBOB/pre-models/steps/make_mfcc.sh --write-utt2num-frames true --mfcc-config /root/kaldi-trunnk/FAKEBOB/pre-models/conf/mfcc.conf --nj 28 --cmd $train_cmd /root/kaldi-trunnk/FAKEBOB/audio-build-model-iv /root/kaldi-trunnk/FAKEBOB/log-build-model-iv /root/kaldi-trunnk/FAKEBOB/mfcc-build-model-iv
/root/kaldi-trunnk/FAKEBOB/pre-models/steps/make_mfcc.sh: line 20: parse_options.sh: No such file or directory
/root/kaldi-trunnk/FAKEBOB/pre-models/sid/compute_vad_decision.sh --nj 28 --cmd $train_cmd --vad-config /root/kaldi-trunnk/FAKEBOB/pre-models/conf/vad.conf /root/kaldi-trunnk/FAKEBOB/audio-build-model-iv /root/kaldi-trunnk/FAKEBOB/log-build-model-iv /root/kaldi-trunnk/FAKEBOB/mfcc-build-model-iv
/root/kaldi-trunnk/FAKEBOB/pre-models/sid/compute_vad_decision.sh: line 18: parse_options.sh: No such file or directory
/root/kaldi-trunnk/FAKEBOB/pre-models/sid/extract_ivectors.sh --cmd $train_cmd --nj 28 --num-threads 1 /root/kaldi-trunnk/FAKEBOB/pre-models /root/kaldi-trunnk/FAKEBOB/audio-build-model-iv /root/kaldi-trunnk/FAKEBOB/ivector-build-model-iv
/root/kaldi-trunnk/FAKEBOB/pre-models/sid/extract_ivectors.sh: line 27: parse_options.sh: No such file or directory
Traceback (most recent call last):
  File "build_spk_models.py", line 185, in <module>
    n_jobs=n_jobs, flag=1, debug=debug)
  File "/root/kaldi-trunnk/FAKEBOB/ivector_PLDA_kaldiHelper.py", line 327, in score_existing
    plda=plda, mean_vec=mean_vec, transform_mat=transform_mat, debug=debug)
  File "/root/kaldi-trunnk/FAKEBOB/ivector_PLDA_kaldiHelper.py", line 272, in plda_scoring
    p = subprocess.Popen(args) if debug else subprocess.Popen(args, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'ivector-plda-scoring'

#### #it seems that something lost in _pre-models_

**Comment by FAKEBOB-adversarial-attack** [comment]
Thanks for your feedback.

We have figured out the reason. This is because ${KALDI_ROOT}/bin, etc are not included in $PATH variable.

We will update the code and instruction soon. You can clone the latest code later. Thanks

**Comment by FAKEBOB-adversarial-attack** [comment]
Hello. The code and README have been updated. 
Please pay attention to the **_6th step_** in the README.
It should work for your problem.
Feel free to contact if you have other problem.
Best.
