### ISSUE TITLE
Is gpu used in Generate adversarial voices 

### ISSUE THREAD

**Issue by wuhao2015** [FAKEBOB-adversarial-attack/FAKEBOB#11]
Hi, thank you for you nice work. I have successfully run the project, however I noticed that my gpu resources remained unused and the attacking step (running attackMain.sh) has taken me more than 18 hours and not finished yet. I wonder if this is because I missed any configurations or this project does not use gpu?
btw how long should an attack process take generally?

**Comment by FAKEBOB-adversarial-attack** [comment]
Hello, currently this project does **NOT** support and use GPU. It is our plan to release GPU version of this project. Stay tuned.

On our machine, for GMM-UBM system, each iteration takes 1-3s; for ivector-PLDA system, each iteration takes 10-15s. To speed up the attack, you can adjust the **n_jobs** parameter (setting it to the number of processors of your machine is a good choice). We recognize that the attack does take quite a long time.

Actually, if you just want to reproduce our experiment, you do not need to generate adversarial voices for all the benign voices. You can manually select **sub set** of test-set (for CSI task) or illegal-set (for OSI / SV task).
