### ISSUE TITLE
Failed building Docker: Unable to establish SSL connection

### ISSUE THREAD

**Issue by GilgameshC** [FAKEBOB-adversarial-attack/FAKEBOB#14]
Hello,
I am unable to build Docker.
> config.status: creating src/extensions/python/Makefile
Unable to establish SSL connection.
Unable to establish SSL connection.
Makefile:185: recipe for target 'cub-1.8.0.tar.gz' failed
make: *** [cub-1.8.0.tar.gz] Error 4
make: *** Waiting for unfinished jobs....
Makefile:166: recipe for target 'sph2pipe-2.5.tar.gz' failed
make: *** [sph2pipe-2.5.tar.gz] Error 4
config.status: creating src/extensions/special/Makefile
config.status: creating src/script/Makefile
config.status: creating config.h
Read error (Connection timed out) in headers.
config.status: creating src/include/fst/config.h
config.status: src/include/fst/config.h is unchanged
config.status: executing depfiles commands

Any suggestions?

Thanks!

**Comment by tom-doerr** [comment]
You ran `./docker/setup.sh`, right?

**Comment by GilgameshC** [comment]
> You ran `./docker/setup.sh`, right?

yes

**Comment by tom-doerr** [comment]
Does the `setup.sh` script actually stop with an error or do you get the "Setup complete!" message at the end?
I just build the docker image successfully but didn't yet check in the command line output whether I get this error as well.

**Comment by GilgameshC** [comment]
> Does the `setup.sh` script actually stop with an error or do you get the "Setup complete!" message at the end?
> I just build the docker image successfully but didn't yet check in the command line output whether I get this error as well.

It is ended with errors.
Just now I tried  `setup.sh` script for several times, and suddenly I succeeded, though I still do not know why......
but I met another problem......

>   File "/usr/local/bin/gdown", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/gdown/cli.py", line 105, in main
    use_cookies=not args.no_cookies,
  File "/usr/local/lib/python2.7/dist-packages/gdown/download.py", line 110, in download
    res = sess.get(url, stream=True)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /u/0/uc?id=1T_hx9Pqopk-rlmiSrBWdXjl825wjBQVF (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f138848ab10>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
tar (child): pre-models.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

**Comment by tom-doerr** [comment]
Looks like there is a problem with your internet connection. You might just want to rerun the setup script a few more times.

**Comment by GolferChen** [comment]
> > Does the `setup.sh` script actually stop with an error or do you get the "Setup complete!" message at the end?
> > I just build the docker image successfully but didn't yet check in the command line output whether I get this error as well.
> 
> It is ended with errors.
> Just now I tried `setup.sh` script for several times, and suddenly I succeeded, though I still do not know why......
> but I met another problem......
> 
> > File "/usr/local/bin/gdown", line 8, in 
> > sys.exit(main())
> > File "/usr/local/lib/python2.7/dist-packages/gdown/cli.py", line 105, in main
> > use_cookies=not args.no_cookies,
> > File "/usr/local/lib/python2.7/dist-packages/gdown/download.py", line 110, in download
> > res = sess.get(url, stream=True)
> > File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 555, in get
> > return self.request('GET', url, **kwargs)
> > File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 542, in request
> > resp = self.send(prep, **send_kwargs)
> > File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 655, in send
> > r = adapter.send(request, **kwargs)
> > File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
> > raise ConnectionError(e, request=request)
> > requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /u/0/uc?id=1T_hx9Pqopk-rlmiSrBWdXjl825wjBQVF (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f138848ab10>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
> > tar (child): pre-models.tgz: Cannot open: No such file or directory
> > tar (child): Error is not recoverable: exiting now
> > tar: Child returned status 2
> > tar: Error is not recoverable: exiting now

The setup will download data from google drive. Maybe you need the proxy. :)

**Comment by GilgameshC** [comment]
> > > Does the `setup.sh` script actually stop with an error or do you get the "Setup complete!" message at the end?
> > > I just build the docker image successfully but didn't yet check in the command line output whether I get this error as well.
> > 
> > 
> > It is ended with errors.
> > Just now I tried `setup.sh` script for several times, and suddenly I succeeded, though I still do not know why......
> > but I met another problem......
> > > File "/usr/local/bin/gdown", line 8, in
> > > sys.exit(main())
> > > File "/usr/local/lib/python2.7/dist-packages/gdown/cli.py", line 105, in main
> > > use_cookies=not args.no_cookies,
> > > File "/usr/local/lib/python2.7/dist-packages/gdown/download.py", line 110, in download
> > > res = sess.get(url, stream=True)
> > > File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 555, in get
> > > return self.request('GET', url, **kwargs)
> > > File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 542, in request
> > > resp = self.send(prep, **send_kwargs)
> > > File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 655, in send
> > > r = adapter.send(request, **kwargs)
> > > File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
> > > raise ConnectionError(e, request=request)
> > > requests.exceptions.ConnectionError: HTTPSConnectionPool(host='drive.google.com', port=443): Max retries exceeded with url: /u/0/uc?id=1T_hx9Pqopk-rlmiSrBWdXjl825wjBQVF (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f138848ab10>: Failed to establish a new connection: [Errno 101] Network is unreachable',))
> > > tar (child): pre-models.tgz: Cannot open: No such file or directory
> > > tar (child): Error is not recoverable: exiting now
> > > tar: Child returned status 2
> > > tar: Error is not recoverable: exiting now
> 
> The setup will download data from google drive. Maybe you need the proxy. :)

Thx. I will try it again :)
