### ISSUE TITLE
New change on loss function

### ISSUE THREAD

**Issue by Li-Chi-Chang** [FAKEBOB-adversarial-attack/FAKEBOB#15]
Hi,

The fakeBob process is stopped by the loss to 0.
However, when I applied the change and found that fakeBob goes to max iterations for every file even if the score is higher than the threshold.
Here is the code clip of stopping check:
![image](https://user-images.githubusercontent.com/59237082/117850966-d45fa600-b253-11eb-8c20-a13dd0fc9710.png)
Here is the new code change of loss fucntion of SV part:
![image](https://user-images.githubusercontent.com/59237082/117851107-fbb67300-b253-11eb-94a7-2b0b07f4b8ca.png)

Thanks

**Comment by FAKEBOB-adversarial-attack** [comment]
Hello, thanks for your feedback. We have changed the early stop condition to fit the updated loss function.

BTW, the reason why we remove from the loss function the outermost maximum operation is that it will cause unexpected issue for benign voices whose **initial loss** is **slightly larger** than **adver_thresh**.

For example, suppose **adver_thresh=0**, and the **initial loss** of a benign voice is 0.01. This voice is not robust enough, so add a random noise is enough to make it adversarial. Hence, the **samples_per_draw** noisy samples are adversarial voices. If the outermost maximum operation is retained, all the loss of these noisy samples are zero. So the estimated gradient remains zero, and the sample will not be updated throughout the iteration procedure.

That 's why we can only achieve 99% ASR, and not 100% in our paper. Using the updated loss function, we can achieve 100% ASR.

**Comment by Li-Chi-Chang** [comment]
Thanks for sharing!
