### ISSUE TITLE
test.py: No such file or directory: 'model/1580.iv'

### ISSUE THREAD

**Issue by TitaniumTTL** [FAKEBOB-adversarial-attack/FAKEBOB#16]
hello, when I enter the docker, run test.py. I face the error: No such file or directory: 'model/1580.iv'

root@c9c5cf113b47:/mounted# python3 test.py
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    with open(path, "rb") as reader:
FileNotFoundError: [Errno 2] No such file or directory: 'model/1580.iv'

I find the dir "model" is empty

**Comment by tom-doerr** [comment]
Did you encounter any issues when running `docker/setup.sh`?

**Comment by TitaniumTTL** [comment]
I met the error:  common_path.sh: No such file or directory
But common_path.sh exists in KALDI_ROOT/tools/config/. I am sad...
+ command_to_execute='python build_spk_models.py'
+++ realpath .
++ basename /data/home/Tiantian_Liu/adversary/FAKEBOB-master
+ [[ FAKEBOB-master == \d\o\c\k\e\r ]]
+ [[ python build_spk_models.py == '' ]]
+ docker run -it --gpus all -v /data/home/Tiantian_Liu/adversary/FAKEBOB-master:/mounted fakebob bash -ic ' \
export KALDI_ROOT=/data/home/Tiantian_Liu/kaldi; \
FAKEBOB_PATH=/data/home/Tiantian_Liu/adversary/FAKEBOB-master/docker; \
export PATH=$FAKEBOB_PATH/pre-models/utils/:$KALDI_ROOT/tools/openfst/bin:$KALDI_ROOT/tools/sph2pipe_v2.5:$PATH; \
[ ! -f $KALDI_ROOT/tools/config/common_path.sh ] && echo >&2 "The standard file $KALDI_ROOT/tools/config/common_path.sh is not present -> Exit!"; \
. $KALDI_ROOT/tools/config/common_path.sh; \
export LC_ALL=C; \
export train_cmd="run.pl --mem 4G"; \
cd /mounted; \
python build_spk_models.py'
The standard file /data/home/Tiantian_Liu/kaldi/tools/config/common_path.sh is not present -> Exit!
bash: /data/home/Tiantian_Liu/kaldi/tools/config/common_path.sh: No such file or directory
bash: python: command not found

**Comment by TitaniumTTL** [comment]
> Did you encounter any issues when running `docker/setup.sh`?

 met the error: common_path.sh: No such file or directory
But common_path.sh exists in KALDI_ROOT/tools/config/. I am sad...

**Comment by FAKEBOB-adversarial-attack** [comment]
Are you sure you only met this error? It seems that you have not successfully built kaldi in `docker/setup.sh`.

**Comment by TitaniumTTL** [comment]
> Are you sure you only met this error? It seems that you have not successfully built kaldi in `docker/setup.sh`.

This is a complete log.
To try another method: manual installation, I also compile Kaldi in my Linux server.

(base) ➜  docker ./setup.sh
Sending build context to Docker daemon  1.744GB
Step 1/28 : from ubuntu:16.04
 ---> 38b3fa4640d4
Step 2/28 : run apt-get update && apt-get install -y  python3-pip git
 ---> Using cache
 ---> 4ff312222acc
Step 3/28 : run python3 --version
 ---> Using cache
 ---> 105f9bd7f33c
Step 4/28 : run pip3 install numpy==1.15
 ---> Using cache
 ---> 64c01c6c9ea7
Step 5/28 : run pip3 install scipy==1.4.0
 ---> Using cache
 ---> f26e66b39f98
Step 6/28 : run pip3 install ushlex
 ---> Using cache
 ---> fa6fe6faeed7
Step 7/28 : run pip3 install pytest-shutil
 ---> Using cache
 ---> 560400301828
Step 8/28 : run git clone https://github.com/FAKEBOB-adversarial-attack/FAKEBOB.git
 ---> Using cache
 ---> 9a982b7f3193
Step 9/28 : env KALDI_ROOT="/kaldi"
 ---> Using cache
 ---> f79b10268338
Step 10/28 : run git clone https://github.com/kaldi-asr/kaldi.git $KALDI_ROOT
 ---> Using cache
 ---> eb0d33daa2d3
Step 11/28 : run cp /FAKEBOB/gmm-global-est-map.cc $KALDI_ROOT/src/gmmbin/
 ---> Using cache
 ---> 1c210b7a956e
Step 12/28 : env makefile_path=$KALDI_ROOT"/src/gmmbin/Makefile"
 ---> Using cache
 ---> 5475f2728a9e
Step 13/28 : run echo $makefile_path
 ---> Using cache
 ---> b382633666e2
Step 14/28 : run ls -la $makefile_path
 ---> Using cache
 ---> a16e28784bb2
Step 15/28 : run changed_content="$(awk '{gsub("BINFILES = ", "BINFILES = gmm-global-est-map \\\n           "); print}' $makefile_path)";     echo "$changed_content" > $makefile_path;     echo ============;     cat $makefile_path
 ---> Using cache
 ---> 64de87b7c49c
Step 16/28 : workdir $KALDI_ROOT/tools
 ---> Using cache
 ---> ace9d6eb13f0
Step 17/28 : run bash extras/install_mkl.sh
 ---> Using cache
 ---> 99001831f667
Step 18/28 : run apt-get install -y zlib1g-dev automake autoconf unzip sox gfortran libtool subversion python2.7
 ---> Using cache
 ---> 7151ee5eedb3
Step 19/28 : run bash extras/check_dependencies.sh
 ---> Using cache
 ---> fc0218ed61f7
Step 20/28 : env NUM_CPUS_TO_USE=24
 ---> Using cache
 ---> d00df7082ebd
Step 21/28 : run make -j $NUM_CPUS_TO_USE
 ---> Using cache
 ---> 5400f5c0ca8a
Step 22/28 : workdir $KALDI_ROOT/src
 ---> Using cache
 ---> 3923241fe9b9
Step 23/28 : run ./configure --shared
 ---> Using cache
 ---> 469fb7b60c4e
Step 24/28 : run cat $makefile_path
 ---> Using cache
 ---> 4d617cdcb865
Step 25/28 : run make depend -j $NUM_CPUS_TO_USE
 ---> Using cache
 ---> 390578e62863
Step 26/28 : run make -j $NUM_CPUS_TO_USE
 ---> Using cache
 ---> 1d4abee3bb8b
Step 27/28 : workdir /kaldi/egs/voxceleb/v1
 ---> Using cache
 ---> 270d187e6db7
Step 28/28 : run echo " export train_cmd=run.pl; export decode_cmd=run.pl; export mkgraph_cmd='run.pl'" > cmd.sh
 ---> Using cache
 ---> 4b5465d33918
Successfully built 4b5465d33918
Successfully tagged fakebob:latest
+ command_to_execute='python build_spk_models.py'
+++ realpath .
++ basename /data/home/Tiantian_Liu/adversary/FAKEBOB-master
+ [[ FAKEBOB-master == \d\o\c\k\e\r ]]
+ [[ python build_spk_models.py == '' ]]
+ docker run -it --gpus all -v /data/home/Tiantian_Liu/adversary/FAKEBOB-master:/mounted fakebob bash -ic ' \
export KALDI_ROOT=/data/home/Tiantian_Liu/kaldi; \
FAKEBOB_PATH=/data/home/Tiantian_Liu/adversary/FAKEBOB-master/docker; \
export PATH=$FAKEBOB_PATH/pre-models/utils/:$KALDI_ROOT/tools/openfst/bin:$KALDI_ROOT/tools/sph2pipe_v2.5:$PATH; \
[ ! -f $KALDI_ROOT/tools/config/common_path.sh ] && echo >&2 "The standard file $KALDI_ROOT/tools/config/common_path.sh is not present -> Exit!"; \
. $KALDI_ROOT/tools/config/common_path.sh; \
export LC_ALL=C; \
export train_cmd="run.pl --mem 4G"; \
cd /mounted; \
python build_spk_models.py'
The standard file /data/home/Tiantian_Liu/kaldi/tools/config/common_path.sh is not present -> Exit!
bash: /data/home/Tiantian_Liu/kaldi/tools/config/common_path.sh: No such file or directory
bash: python: command not found

**Comment by TitaniumTTL** [comment]
I am sorry. I have already found the mistake that I modify Kaldi_ROOT and FAKEBOB_ROOT in run.sh.
and I also found that the last line should be modified as python3 build_spk_model.py rather than python ...
Now I am running build_spk_model.py 
Maybe I will face new mistake (I hope not)

**Comment by TitaniumTTL** [comment]
I have successfully run scripts in docker environment
this issue may be closed

**Comment by FAKEBOB-adversarial-attack** [comment]
Great. Issue closed.
