### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ivector-plda-scoring'

### ISSUE THREAD

**Issue by jk299** [FAKEBOB-adversarial-attack/FAKEBOB#19]
I followed the Manual installation and in the step-7, when running **build_spk_models.py**, I met FileNotFoundError.
I'm not sure where's the command 'ivector-plda-scoring'.

**Comment by jk299** [comment]
----- step 1: generate ivector identity and corresponding speaker model -----
--- extracting and scoring ---
Traceback (most recent call last):
  File "build_spk_models.py", line 112, in <module>
    iv_helper.score_existing(audio_path_list, enroll_utt_id, spk_id_list=spk_id_list,
  File "/home/henry/Project/SR_project/FAKEBOB/ivector_PLDA_kaldiHelper.py", line 331, in score_existing
    self.plda_scoring(train_ivector_scp=train_ivector_scp, test_ivector_scp=test_ivector_scp, trials_file=trials_file, scores_file=scores_file, 
  File "/home/henry/Project/SR_project/FAKEBOB/ivector_PLDA_kaldiHelper.py", line 277, in plda_scoring
    p = subprocess.Popen(args) if debug else subprocess.Popen(args, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ivector-plda-scoring'

**Comment by GolferChen** [comment]
So weird. Several older issues also reported the same problem, but I have tested the manual installation from scratch on a new machine and found everything working properly.

What is your shell type? Could you run `echo $0` and `which ivector-plda-scoring` and provide the output capture?

**Comment by jk299** [comment]
Thanks for you reply. I have solved this problem, which caused by failing to install the kaldi.
In the kaldi/src/INSTALL, the jobs was set too many for my laptop, causing failed compilation.

**Comment by FAKEBOB-adversarial-attack** [comment]
> Thanks for you reply. I have solved this problem, which caused by failing to install the kaldi. In the kaldi/src/INSTALL, the jobs was set too many for my laptop, causing failed compilation.

Happy to hear this. Issued Closed.
