### ISSUE TITLE
ERRO[0001] error waiting for container: context canceled

### ISSUE THREAD

**Issue by drrain92** [FAKEBOB-adversarial-attack/FAKEBOB#20]
Hi there,
I followed the docker instruction to run 'docker/setup.sh', but have the following problem:

export PATH=$FAKEBOB_PATH/pre-models/utils/:$KALDI_ROOT/tools/openfst/bin:$KALDI_ROOT/tools/sph2pipe_v2.5:$PATH; \
[ ! -f $KALDI_ROOT/tools/config/common_path.sh ] && echo >&2 "The standard file $KALDI_ROOT/tools/config/common_path.sh is not present -> Exit!" && exit 1; \
. $KALDI_ROOT/tools/config/common_path.sh; \
export LC_ALL=C; \
export train_cmd="run.pl --mem 4G"; \
cd /mounted; \
python3 build_spk_models.py'
docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
ERRO[0001] error waiting for container: context canceled 

Could you help me to solve this problem?
Thanks,

**Comment by SHUJAA14** [comment]
> Hi there, I followed the docker instruction to run 'docker/setup.sh', but have the following problem:
> 
> export PATH=$FAKEBOB_PATH/pre-models/utils/:$KALDI_ROOT/tools/openfst/bin:$KALDI_ROOT/tools/sph2pipe_v2.5:$PATH; [ ! -f $KALDI_ROOT/tools/config/common_path.sh ] && echo >&2 "The standard file $KALDI_ROOT/tools/config/common_path.sh is not present -> Exit!" && exit 1; . $KALDI_ROOT/tools/config/common_path.sh; export LC_ALL=C; export train_cmd="run.pl --mem 4G"; cd /mounted; python3 build_spk_models.py' docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]]. ERRO[0001] error waiting for container: context canceled

> Could you help me to solve this problem? Thanks,



> Sorry to bother you ,, Did you know how to solve this issue, I am facing the same problem 
thanks a lot

**Comment by drrain92** [comment]
Hi there, 
I just use another computer to set up the environment and bypass this problem. There is no issue with the code, but something wrong with my system or configuration.
Hope this can help you.

**Comment by SHUJAA14** [comment]
> Hi there, I just use another computer to set up the environment and bypass this problem. There is no issue with the code, but something wrong with my system or configuration. Hope this can help you.

Thank you so very much for your quick reply. I will keep trying.
