### ISSUE TITLE
Add enrollment error

### ISSUE THREAD

**Issue by Mars0313** [FAKEBOB-adversarial-attack/FAKEBOB#21]
When I add other voice to data/enrollment-set and run build_spk_models.py I got the following error message:
how can i add other voice to enrollment

----- step 1: generate ivector identity and corresponding speaker model -----
--- extracting and scoring ---
--- extracting and scoring done---
--- resolve score and obtain z norm mean and std value ---
/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py:2920: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py:140: RuntimeWarning: Degrees of freedom <= 0 for slice
  keepdims=keepdims)
/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py:110: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/usr/local/lib/python3.5/dist-packages/numpy/core/_methods.py:132: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
--- resolve score, and obtain z norm mean and std value done ---
--- dump speaker unique model ---
Traceback (most recent call last):
  File "build_spk_models.py", line 150, in <module>
    ivectors_location[np.argwhere(ivectors_utt == utt_id).flatten()[0]])  # use absolute path
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by FAKEBOB-adversarial-attack** [comment]
I guess you have to make sure the name of your added wav follows the format of 'SPKID-X-Y.wav'.

**Comment by robert-YZ** [comment]
> I guess you have to make sure the name of your added wav follows the format of 'SPKID-X-Y.wav'.

Yes my wav's format is  SPKID-X-Y.wav'.

**Comment by GuangkeChen** [comment]
Could you print the variables ``ivectors_utt``  and ``utt_id`` before Line 150 and show me the result?
