### ISSUE TITLE
problem in step 8 running 'test.py' about 'data'

### ISSUE THREAD

**Issue by KujouAika** [FAKEBOB-adversarial-attack/FAKEBOB#8]
A data called '1580-141084-0049.wav' in '1580' is a shortcut with 0 bytes.

Traceback (most recent call last):
  File "./test.py", line 90, in <module>
    _, audio = read(path)
  File "/home/neu/anaconda3/lib/python3.8/site-packages/scipy/io/wavfile.py", line 544, in read
    fid = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: './data/test-set/1580/1580-141084-0049.wav'
![QQ截图20201013085336](https://user-images.githubusercontent.com/48083187/95803022-9dfb9000-0d31-11eb-8f80-fa03189449e1.png)

**Comment by KujouAika** [comment]
btw, its MD5 is 1897f23e9628cc54bdbf455998ce11c2. I downloaded from google drive and I'm not sure why it differs from MD5 43934261ea3e200064f00573ada01d6d in 'readme'.

**Comment by KujouAika** [comment]
There is the same problem with:
'4446-2275-0043.wav', 
'5142-36600-0000.wav', 
'61-70970-0039.wav', 
'61-70970-0040.wav'
I downloaded the dataset in LibriSpeech and found the files. Then I successfully converted the FLAC to WAV and put it into the dataset, its working

**Comment by GolferChen** [comment]
Hello, glad to hear that it works. But actually this problem has already been fixed (someone have pointed out this in issue). Make sure you download the latest data.tgz and check the MD5.

**Comment by KujouAika** [comment]
Thank you for your email！
Yes I saw the issue after my submission.Thank you！

发自我的iPhone


------------------ Original ------------------
